[package]
name = "murmur"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A utility for printing colored and formatted messages to the terminal"

[dependencies]
once_cell = "1.19.0"
owo-colors = "3.5.0"
tracing = { version = "0.1.40", optional = true }

[features]
default = []
