[env]
VERSION = "1.2.1"

[tasks.cargo-fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.cargo-set-version]
install_crate = "cargo-edit"
command = "cargo"
args = ["set-version", "${VERSION}"]

[tasks.cargo-clean-release]
command = "cargo"
args = ["clean", "--release"]

[tasks.cargo-doc]
command = "cargo"
args = ["doc", "--no-deps", "--document-private-items"]

[tasks.cargo-build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.git-add-all]
command = "git"
args = ["add", "--all"]

[tasks.git-commit]
command = "git"
args = ["commit", "-m", "Release v${VERSION}"]

[tasks.git-tag]
command = "git"
args = ["tag", "v${VERSION}"]

[tasks.git-push]
command = "git"
args = ["push"]

[tasks.git-push-tag]
command = "git"
args = ["push", "origin", "v${VERSION}"]

[tasks.gh-release]
command = "gh"
args = ["release", "create", "v${VERSION}", "-F", "CHANGELOG.md"]

[tasks.cargo-bin]
command = "cargo"
args = ["bin"]

[tasks.cargo-devlog-clean]
command = "cargo"
args = ["devlog"]

[tasks.lazy]
command = "lazy"

[tasks.cargo-readme]
command = "cargo"
args = ["readme"]

[tasks.cargo-publish]
command = "cargo"
args = ["publish"]

[tasks.release]
dependencies = [
    "cargo-fmt",
    "cargo-set-version",
    "cargo-clean-release",
    "cargo-readme",
    "cargo-doc",
    "cargo-build-release",
    "git-add-all",
    "git-commit",
    "git-tag",
    "git-push",
    "git-push-tag",
    "cargo-devlog-clean",
    "gh-release",
    "cargo-publish",
]