[env]
VERSION = "1.1.0"

[tasks.cargo-build-release]
args = [
    "build",
    "--release",
]
command = "cargo"

[tasks.cargo-clean-release]
args = [
    "clean",
    "--release",
]
command = "cargo"

[tasks.cargo-doc]
args = [
    "doc",
    "--no-deps",
    "--document-private-items",
]
command = "cargo"

[tasks.cargo-edit-set-version]
args = [
    "set-version",
    "${VERSION}",
]
command = "cargo"
install_crate = "cargo-edit"

[tasks.cargo-fmt]
args = ["fmt"]
command = "cargo"
install_crate = "rustfmt"

[tasks.cargo-publish]
args = ["publish"]
command = "cargo"

[tasks.gh-release]
args = [
    "release",
    "create",
    "v${VERSION}",
    "-F",
    "CHANGELOG.md",
]
command = "gh"

[tasks.git-add-all]
args = [
    "add",
    "--all",
]
command = "git"

[tasks.git-commit]
args = [
    "commit",
    "-m",
    "Release: v${VERSION}",
]
command = "git"

[tasks.git-push]
args = ["push"]
command = "git"

[tasks.git-push-tag]
args = [
    "push",
    "origin",
    "v${VERSION}",
]
command = "git"

[tasks.git-tag]
args = [
    "tag",
    "v${VERSION}",
]
command = "git"

[tasks.release]
dependencies = [
    "cargo-fmt",
    "cargo-edit-set-version",
    "cargo-clean-release",
    "cargo-doc",
    "cargo-build-release",
    "git-add-all",
    "git-commit",
    "git-tag",
    "git-push",
    "git-push-tag",
    "gh-release",
    "cargo-publish",
]
